#!/bin/bash

echo "DEBUG: $0 fake"
while getopts "qt:n:" opt; do
    case $opt in
        q)
            QUIET=1
            ;;
        t)
            TEMPLATE="$OPTARG"
		echo "DEBUG: getopt TEMPLATE=$TEMPLATE"
            ;;
        n)
            LXC_NAME="$OPTARG"
		echo "DEBUG: getopt LXC_NAME=$LXC_NAME"
            ;;
        *)
            ;;
    esac
done

if [ -z "$LXC_NAME" ];then
	echo "ERROR: need a LXC_NAME"
	exit 1
fi

mkdir -p /var/lib/lxc/${LXC_NAME}/rootfs/bin || exit $?

exit 0
