#!/bin/bash

echo "DEBUG: $0 fake"
CMD=$(awk -F'-- ' '{print $2}' <<< "$@")

while getopts "n:v:" opt; do
    case $opt in
        n)
            LXC_NAME="$OPTARG"
            ;;
        v)
            export "$OPTARG"
            ;;
        *)
            ;;
    esac
done

if [ ! -e /var/lib/lxc/${LXC_NAME} ];then
	echo "ERROR: ${LXC_NAME} does not exists"
	exit 1
fi

find /var/lib/lxc/${LXC_NAME} -iname 'lava-[0-9]*' |
while read line
do
	LAVA_NAME=$(basename $line)
	echo "DEBUG: handle $line"
	ln -s "$line" "/$LAVA_NAME"
done

if [ "$CMD" ]; then
	echo "DEBUG: lxc-attach-mocker in ${LXC_NAME}"
	# execute the given command
	$CMD
else
    # when no commands are requested, open up a shell
    /bin/bash
fi
exit $?
